import { FormEvent, useEffect, useState } from 'react'
import { api } from '../lib/api'
import type { AiConfiguration, AiProviderType } from '../types'

const defaults: Record<AiProviderType, string> = { OPENAI: 'gpt-4.1-mini', GOOGLE_GENAI: 'gemini-2.5-flash' }

export default function AiSettingsPage() {
  const [configuration, setConfiguration] = useState<AiConfiguration>()
  const [provider, setProvider] = useState<AiProviderType>('OPENAI')
  const [model, setModel] = useState(defaults.OPENAI)
  const [enabled, setEnabled] = useState(true)
  const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  useEffect(() => { void load() }, [])
  async function load() { try { const current = await api.getAiConfiguration(); setConfiguration(current); if (current.provider) { setProvider(current.provider); setModel(current.model ?? defaults[current.provider]); setEnabled(current.enabled) } } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tải cấu hình AI') } finally { setLoading(false) } }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const key = String(new FormData(event.currentTarget).get('apiKey') ?? '').trim(); setSaving(true); setError(''); setMessage(''); try { setConfiguration(await api.saveAiConfiguration({ provider, model, ...(key ? { apiKey: key } : {}), enabled })); setMessage('Đã lưu cấu hình an toàn. API key không được hiển thị lại.'); event.currentTarget.reset() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể lưu cấu hình') } finally { setSaving(false) } }
  async function testConnection() { setSaving(true); setError(''); setMessage(''); try { setMessage((await api.testAiConfiguration()).message) } catch (e) { setError(e instanceof Error ? e.message : 'Không thể kiểm tra AI provider') } finally { setSaving(false) } }
  async function remove() { if (!confirm('Xóa khóa AI đã lưu?')) return; setSaving(true); setError(''); try { await api.deleteAiConfiguration(); setConfiguration({ configured: false, provider: null, model: null, enabled: false, keySuffix: null, updatedAt: null }); setMessage('Đã xóa cấu hình AI.') } catch (e) { setError(e instanceof Error ? e.message : 'Không thể xóa cấu hình') } finally { setSaving(false) } }
  if (loading) return <p className="loading">Đang tải cấu hình AI…</p>
  return <section className="page-stack settings-page"><div><p className="eyebrow">PERSONAL WORKSPACE</p><h1>Thiết lập AI</h1><p>Chọn provider, model và khóa riêng cho các phiên phân tích mới.</p></div><div className="info-panel"><strong>Khóa được bảo vệ ở server</strong><span>Key được mã hóa AES-GCM trước khi vào database, không được trả lại browser hoặc ghi log.</span></div>{configuration?.configured && <div className="ai-banner"><div><strong>{configuration.provider} · {configuration.model}</strong><span>Key: ••••{configuration.keySuffix} · {configuration.enabled ? 'Đang bật' : 'Đang tắt'}</span></div></div>}<form className="analysis-form" onSubmit={save}><label>AI provider<select value={provider} onChange={e => { const next = e.target.value as AiProviderType; setProvider(next); if (model === defaults[provider]) setModel(defaults[next]) }}><option value="OPENAI">OpenAI</option><option value="GOOGLE_GENAI">Google Gemini</option></select></label><label>Model<input value={model} onChange={e => setModel(e.target.value)} required maxLength={100} pattern="[A-Za-z0-9._:-]+" /></label><label>API key {configuration?.configured ? '(để trống nếu giữ nguyên)' : ''}<input name="apiKey" type="password" required={!configuration?.configured} minLength={8} maxLength={512} autoComplete="new-password" spellCheck={false} /></label><label className="switch-label"><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)} /> Bật AI cho phiên mới</label>{error && <p className="error">{error}</p>}{message && <p className="success">{message}</p>}<div className="form-actions">{configuration?.configured && <button type="button" className="secondary" disabled={saving} onClick={() => void testConnection()}>Kiểm tra kết nối</button>}{configuration?.configured && <button type="button" className="secondary danger-text" disabled={saving} onClick={() => void remove()}>Xóa cấu hình</button>}<button disabled={saving}>{saving ? 'Đang lưu…' : 'Lưu cấu hình an toàn'}</button></div></form></section>
}
